server:
  port: 9090
  servlet:
    context-path: /user
  tomcat:
    accesslog:
      buffered: true
      directory: /home/logs/tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: '%t | %{X-Real-IP}i | %b | %B | %H | %l | %m | %p | %q | %r | %s | %S | %u | %U | %v | %D | %T | %{Cookie}i | %{User-Agent}i | %{a}r'
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
spring:
  application:
    name: support
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: Mysql!@#456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000
mybatis-plus:
#  mapper-locations: classpath*:com/wfmyzyz/user/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 删除
      logic-not-delete-value: 正常
      logic-delete-field: tb_status
logging:
  level:
    com.wfmyzyz.user.user.mapper: debug